### ISSUE TITLE
VERSA 2 - no items transfered

### ISSUE THREAD

**Issue by hklages** [abhijitvalluri/fitbit-todo-list#6]
Hi I installed the app on Fitbit VERSA 2. 
Installation went well but I am not able to transfer any items to the VERSA 2. 
Can you please check?

**Comment by abhijitvalluri** [comment]
Hi,

I'm no longer actively developing the app. I don't own a versa or versa 2
so I will be unable to test this and debug it.

Regards,
Abhijit

**Comment by hklages** [comment]
Thanks for the quick response!
I did a hard reset (the typical solution for everything) and now it works.

Have a nice day, Henning
